# Generated by Django 4.0.3 on 2022-03-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Box_tqty', models.CharField(max_length=10)),
                ('Box_line', models.CharField(max_length=30)),
                ('Box_operator', models.CharField(max_length=30)),
                ('Box_data_production', models.DateField()),
                ('Box_shift_closed', models.CharField(choices=[('1', '1º'), ('2', '2º'), ('3', '3º')], max_length=1)),
                ('Box_Product', models.CharField(choices=[('C', 'Charger'), ('B', 'Battery')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Palletqty', models.CharField(max_length=10)),
                ('line', models.CharField(max_length=30)),
                ('operator', models.CharField(max_length=30)),
                ('data_production', models.DateField()),
                ('shift_closed', models.CharField(choices=[('1', '1º'), ('2', '2º'), ('3', '3º')], max_length=1)),
            ],
        ),
    ]
